name: News Auto Deploy

on:
  schedule:
    - cron: "0 * * * *"  # 每小时执行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests beautifulsoup4 markdown

    - name: Run scraper and build
      run: |
        python generator/scraper.py
        python generator/build_articles.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
